version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      
  rails: &rails
    build: .
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  console:
    <<: *rails
    command: /bin/bash -c "bundle install && rails c"
    ports:
      - 3000

  runner:
    <<: *rails
    command: /bin/bash
    ports:
      - 3000